zeichen32_git_lab_api:
  clients:
    firstclient:
      token: your-api-token
      url: http://example.org/api/v3/
      auth_method: http_token
    secondclient:
      token: your-api-token
      url: http://example.org/api/v3/
      auth_method: oauth_token
      sudo: 1
    thirdclient:
      token: your-api-token
      url: http://example.org/api/v3/
      alias: custom_alias